version: 3

services:
	nginx:
		image: nginx:latest
		ports:
			- 80:80
		volumes:
			- ./nginx:/etc/nginx

	db:
		image: mariadb
		volumes:
			- ./mariadb:/var/lib/mysql
		ports:
			- 3306:3306
		environment:
			- MYSQL_ROOT_PASSWORD=asdasdfasdfas
