version: "3"

services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx:/etc/nginx/conf.d/
    depends_on:
      - django

  mariadb:
    image: mariadb
    volumes:
      - ./mariadb:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=asdasdfasdfas
      - MYSQL_DATABASE=hola

  django:
    build:
      context: ./django
      dockerfile: Dockerfile
    volumes:
      - ./django:/app
    depends_on:
      - mariadb
